"""Generate a self-contained serve.sh script for the drive."""

import os
import stat
from pathlib import Path

SERVE_SH = r'''#!/usr/bin/env bash
set -euo pipefail

# ── Primer · Offline Server Launcher ──────────────────────────────────────────
# Auto-generated by primer. Start kiwix-serve, go-pmtiles, or llama-server
# from content on this drive.

DRIVE_ROOT="$(cd "$(dirname "$0")" && pwd)"
PIDS=()

cleanup() {
    echo ""
    echo "Shutting down..."
    for pid in "${PIDS[@]}"; do
        kill "$pid" 2>/dev/null && echo "  Stopped PID $pid" || true
    done
    exit 0
}
trap cleanup SIGINT SIGTERM

# ── Detect platform ──────────────────────────────────────────────────────────

detect_platform() {
    local os arch
    case "$(uname -s)" in
        Darwin*) os="macos" ;;
        Linux*)  os="linux" ;;
        *)       os="unknown" ;;
    esac
    case "$(uname -m)" in
        x86_64)  arch="x86_64" ;;
        aarch64) arch="arm64" ;;
        arm64)   arch="arm64" ;;
        *)       arch="unknown" ;;
    esac
    echo "${os}-${arch}"
}

PLATFORM="$(detect_platform)"
BIN_DIR="$DRIVE_ROOT/bin"
echo "Platform: $PLATFORM"
echo "Drive:    $DRIVE_ROOT"
echo ""

# ── Find binaries ────────────────────────────────────────────────────────────

find_binary() {
    local name="$1"
    # Check platform-specific directory first
    for dir in "$BIN_DIR/$PLATFORM" "$BIN_DIR"; do
        if [ -x "$dir/$name" ]; then
            echo "$dir/$name"
            return 0
        fi
    done
    # Fall back to PATH
    if command -v "$name" >/dev/null 2>&1; then
        command -v "$name"
        return 0
    fi
    return 1
}

KIWIX_BIN="$(find_binary kiwix-serve 2>/dev/null || true)"
PMTILES_BIN="$(find_binary go-pmtiles 2>/dev/null || true)"
LLAMA_BIN="$(find_binary llama-server 2>/dev/null || true)"

# ── Count content ────────────────────────────────────────────────────────────

count_files() {
    local pattern="$1"
    local dir="$2"
    if [ -d "$dir" ]; then
        find "$dir" -name "$pattern" -type f 2>/dev/null | wc -l | tr -d ' '
    else
        echo "0"
    fi
}

ZIM_COUNT=$(count_files "*.zim" "$DRIVE_ROOT/zim")
PMTILES_COUNT=$(count_files "*.pmtiles" "$DRIVE_ROOT/maps")
GGUF_COUNT=$(count_files "*.gguf" "$DRIVE_ROOT/models")

echo "Content found:"
[ "$ZIM_COUNT" -gt 0 ] && echo "  ZIM files:    $ZIM_COUNT"
[ "$PMTILES_COUNT" -gt 0 ] && echo "  PMTiles maps: $PMTILES_COUNT"
[ "$GGUF_COUNT" -gt 0 ] && echo "  GGUF models:  $GGUF_COUNT"

if [ "$ZIM_COUNT" -eq 0 ] && [ "$PMTILES_COUNT" -eq 0 ] && [ "$GGUF_COUNT" -eq 0 ]; then
    echo "  (no content files found — run 'primer sync' first)"
    exit 0
fi
echo ""

# ── Collect ZIM files (including zim/custom/) ────────────────────────────────

collect_zim_files() {
    local files=()
    if [ -d "$DRIVE_ROOT/zim" ]; then
        while IFS= read -r f; do
            files+=("$f")
        done < <(find "$DRIVE_ROOT/zim" -name "*.zim" -type f 2>/dev/null)
    fi
    printf '%s\n' "${files[@]}"
}

# ── Service launchers ────────────────────────────────────────────────────────

start_kiwix() {
    local port="${1:-8080}"
    if [ -z "$KIWIX_BIN" ]; then
        echo "Error: kiwix-serve not found"
        return 1
    fi
    local zim_files=()
    while IFS= read -r f; do
        [ -n "$f" ] && zim_files+=("$f")
    done < <(collect_zim_files)
    if [ ${#zim_files[@]} -eq 0 ]; then
        echo "No ZIM files found."
        return 1
    fi
    echo "Starting kiwix-serve on port $port with ${#zim_files[@]} ZIM files..."
    "$KIWIX_BIN" --port "$port" "${zim_files[@]}" &
    PIDS+=($!)
    echo "  Kiwix:  http://localhost:$port"
}

start_pmtiles() {
    local port="${1:-8081}"
    if [ -z "$PMTILES_BIN" ]; then
        echo "Error: go-pmtiles not found"
        return 1
    fi
    echo "Starting go-pmtiles on port $port..."
    "$PMTILES_BIN" serve "$DRIVE_ROOT/maps" --port "$port" &
    PIDS+=($!)
    echo "  Maps:   http://localhost:$port"
}

start_llama() {
    local port="${1:-8082}"
    if [ -z "$LLAMA_BIN" ]; then
        echo "Error: llama-server not found"
        return 1
    fi
    local model
    model="$(find "$DRIVE_ROOT/models" -name "*.gguf" -type f 2>/dev/null | head -1)"
    if [ -z "$model" ]; then
        echo "No GGUF model found."
        return 1
    fi
    echo "Starting llama-server on port $port with $(basename "$model")..."
    "$LLAMA_BIN" -m "$model" --port "$port" &
    PIDS+=($!)
    echo "  LLM:    http://localhost:$port"
}

# ── Menu ─────────────────────────────────────────────────────────────────────

show_menu() {
    echo "Available services:"
    echo ""
    local n=0
    if [ "$ZIM_COUNT" -gt 0 ] && [ -n "$KIWIX_BIN" ]; then
        echo "  1) Kiwix     — browse $ZIM_COUNT ZIM files (Wikipedia, etc.)"
        n=$((n + 1))
    fi
    if [ "$PMTILES_COUNT" -gt 0 ] && [ -n "$PMTILES_BIN" ]; then
        echo "  2) Maps      — serve $PMTILES_COUNT PMTiles map files"
        n=$((n + 1))
    fi
    if [ "$GGUF_COUNT" -gt 0 ] && [ -n "$LLAMA_BIN" ]; then
        echo "  3) LLM       — run local language model"
        n=$((n + 1))
    fi
    echo "  a) All available services"
    echo "  q) Quit"
    echo ""

    if [ "$n" -eq 0 ]; then
        echo "No services available. Install server binaries or run 'primer sync'."
        exit 0
    fi

    read -rp "Choose> " choice
    case "$choice" in
        1) start_kiwix ;;
        2) start_pmtiles ;;
        3) start_llama ;;
        a|A)
            [ "$ZIM_COUNT" -gt 0 ] && [ -n "$KIWIX_BIN" ] && start_kiwix
            [ "$PMTILES_COUNT" -gt 0 ] && [ -n "$PMTILES_BIN" ] && start_pmtiles
            [ "$GGUF_COUNT" -gt 0 ] && [ -n "$LLAMA_BIN" ] && start_llama
            ;;
        q|Q) exit 0 ;;
        *) echo "Invalid choice." ; show_menu ;;
    esac
}

# ── Main ─────────────────────────────────────────────────────────────────────

show_menu

if [ ${#PIDS[@]} -gt 0 ]; then
    echo ""
    echo "Services running. Press Ctrl+C to stop all."
    wait
fi
'''


def generate_serve_sh(drive_path: Path) -> Path:
    """Write serve.sh to the drive root and make it executable."""
    dest = drive_path / "serve.sh"
    dest.write_text(SERVE_SH)
    dest.chmod(dest.stat().st_mode | stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR |
               stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)
    return dest
